### ISSUE TITLE
NonLockingUniqueUpdater

### ISSUE THREAD

**Issue by Andrewsville** [Kdyby/Doctrine#202]
Do you plan to create an update equivalent of NonLockingUniqueInserter?

I believe the actual process would be very close to NonLockingUniqueInserter:
1. Generate the SQL update query.
2. Try to execute the query.
3. If an unique constraint is violated, return FALSE.
4. Somehow tell Doctrine that the current entity state is unchanged.

Obviously the (4) is the problem here, because you can detach & merge the entity but you would get another instance - no relations possible until updated. And I believe that that's a way bigger issue than when the entity is new. Unfortunately I don't know any other way to tell Doctrine to forget that there were no changes to the entity made and to consider the current state unchanged.

**Comment by fprochazka** [comment]
Hmm, I never really needed it so far, but we may think about it.

Merging in the inserter is there only because the ID is autogenerated and there is no easier way to force doctrine to use it apart from the merge function.
Updater could be easier to hack. I believe we can fake the orignal data for the entity in UoW.

**Comment by Andrewsville** [comment]
We can try to prepare a PR in a week or two (we need it but not that much :)).

**Comment by fprochazka** [comment]
@Andrewsville It's up to you, no hurry :)

**Comment by fprochazka** [comment]
I guess it's out of scope now.
