### ISSUE TITLE
orm:ensure-production-settings

### ISSUE THREAD

**Issue by jasin755** [Kdyby/Doctrine#237]
When I use this command: "orm:ensure-production-settings" it always outputs "Proxy Classes are always regenerating". Is it true that proxies are always regenerated or that command isn't 100% sure?

**Comment by fprochazka** [comment]
It's not automatically registered here https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/DI/console.neon for a reason - it's not supported. So it's output might not be entirely valid. Nette doesn't have a standard way of telling what environment is running in console, so there is really no easy way of solving this, since the console might be in different mode than the webapp which invalidates the command results entirely.

I've went through the code that setups proxies and found out, it could be optimized a bit. Since the `Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition()` doesn't call the autoloader, it was doing one useless `file_exists()` call. Problem is this might be considered a BC Break, so I'm not sure if I should release it in `3.*`.

**Comment by fprochazka** [comment]
I'm gonna leave it in the master for a bit and we'll see if somebody has any ideas for this.

**Comment by enumag** [comment]
@fprochazka Does this mean I need to call some command after deploying new version?

**Comment by fprochazka** [comment]
@enumag yes, ofcourse - you have to do that either way. The proxies won't re-generate themselves. I guess a few lines in the documentation should be added about this.

**Comment by fprochazka** [comment]
If there is anything that could be done to properly setup production settings automatically please open an issue so we can discuss and solve it. But I don't think it makes sense to support this command as is because of the way environments and debug mode works in Nette. Maybe that will change in the future.
