### ISSUE TITLE
A DB connection is opened even if it doesn't (?) really have to

### ISSUE THREAD

**Issue by Andrewsville** [Kdyby/Doctrine#264]
The problem is quite simple. Use Kdyby\Doctrine, have a couple of queries, cache them (using the query cache) and fire a page that loads all query results from cache. Kdyby\Doctrine will still connect to the database, because of [this](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/Connection.php#L314) (invoked by [creating a new hydrator](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php#L103)). 

It was introduced by [this commit](https://github.com/Kdyby/Doctrine/commit/2bd7589ae87a8d797b12361a136f0f292bb956a1). As far as I understand it is about [this foreach](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/Connection.php#L282) but the current state makes it impossible to not connect to the database even if all query results are cached.

**Comment by fprochazka** [comment]
[Since 2.5.something](https://github.com/doctrine/dbal/commit/3176f51d1426022d305c6531a9b9bc93a868bddd) Doctrine [requires connection to create the `*Platform` object](https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Connection.php#L384-L401), because it checks the version of the database as first query. Kdyby actually hacks that so it connects only when you touch the connection, otherwise it was always connecting right away.

The only way to optimize this further is IMHO resolve it compile-time and push it as a dependency using `$params['platform']`.

**Comment by fprochazka** [comment]
I intend to refactor the creation of Connection as a part of [v4.0](https://github.com/Kdyby/Doctrine/milestones/v4.0) to make it somehow more simple and less magic - which would hopefully allow this to be lazier.

**Comment by Andrewsville** [comment]
AFAIK (and according to my tests) you can bypass that by providing ```platform``` and ```serverVersion``` in configuration (which is not a problem since both very, very rarely change). And Doctrine then doesn't need to connect at all.

**Comment by fprochazka** [comment]
Anyway, I agree it's a bug.

**Comment by lookyman** [comment]
@Andrewsville Can you show the config you used to bypass this issue?

**Comment by Andrewsville** [comment]
@lookyman 
We have added this to our (Kdyby\Doctrine) configuration:

```
plaform: pdo_mysql
serverVersion: 5.5
```

This prevents Doctrine from autodetecting platform and version (which results in a connection attempt).

And then we have created [this simple class](https://gist.github.com/Andrewsville/b8549a1112406c2c84369ebbdfb9aed4) and used it as wrapperCalss (again in Kdyby\Doctrine configuration):

```
wrapperClass: Biano\Doctrine\Connection
```

Honestly, I don't know how to reproduce the bug that resulted in the commit mentioned in the original issue so maybe this fix won't eliminate it but this solution has been working for us for a couple of weeks.

**Comment by fprochazka** [comment]
I have come across this with a symfony project too. Few notes

* the default autodetection is desired
* providing the platform and server version to prevent autodetection is the right way to solve this
* the hacks with connection types etc will be removed in master as part of [v4.0](https://github.com/Kdyby/Doctrine/milestones/v4.0)

I'm closing this for now, since it can be "solved" by configuration. Thank you for reporting this and thorough investigation!
